const Price_data = [
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Cabbage",
      "variety": "Cabbage",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "800",
      "max_price": "1000",
      "modal_price": "900"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Ginger(Green)",
      "variety": "Green Ginger",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "4500",
      "max_price": "4700",
      "modal_price": "4600"
    },
    {
      "state": "Uttar Pradesh",
      "district": "Bareilly",
      "market": "Richha",
      "commodity": "Rice",
      "variety": "Common",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "2450",
      "max_price": "2480",
      "modal_price": "2465"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Brinjal",
      "variety": "Arkasheela Mattigulla",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "1500",
      "max_price": "1800",
      "modal_price": "1600"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Guava",
      "variety": "Guava",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "3500",
      "max_price": "3700",
      "modal_price": "3600"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Peas cod",
      "variety": "Other",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "1500",
      "max_price": "1700",
      "modal_price": "1600"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Tomato",
      "variety": "Deshi",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "1400",
      "max_price": "1600",
      "modal_price": "1500"
    },
    {
      "state": "Tamil Nadu",
      "district": "Coimbatore",
      "market": "Pudupalayam",
      "commodity": "Coconut",
      "variety": "Coconut",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "2400",
      "max_price": "2600",
      "modal_price": "2500"
    },
    {
      "state": "Uttar Pradesh",
      "district": "Bareilly",
      "market": "Richha",
      "commodity": "Paddy(Dhan)(Common)",
      "variety": "Common",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "2030",
      "max_price": "2055",
      "modal_price": "2040"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Banana",
      "variety": "Amruthapani",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "1800",
      "max_price": "2000",
      "modal_price": "1900"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Cabbage",
      "variety": "Cabbage",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "800",
      "max_price": "1000",
      "modal_price": "900"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Ginger(Green)",
      "variety": "Green Ginger",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "4500",
      "max_price": "4700",
      "modal_price": "4600"
    },
    {
      "state": "Uttar Pradesh",
      "district": "Bareilly",
      "market": "Richha",
      "commodity": "Rice",
      "variety": "Common",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "2450",
      "max_price": "2480",
      "modal_price": "2465"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Brinjal",
      "variety": "Arkasheela Mattigulla",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "1500",
      "max_price": "1800",
      "modal_price": "1600"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Guava",
      "variety": "Guava",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "3500",
      "max_price": "3700",
      "modal_price": "3600"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Peas cod",
      "variety": "Other",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "1500",
      "max_price": "1700",
      "modal_price": "1600"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Tomato",
      "variety": "Deshi",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "1400",
      "max_price": "1600",
      "modal_price": "1500"
    },
    {
      "state": "Tamil Nadu",
      "district": "Coimbatore",
      "market": "Pudupalayam",
      "commodity": "Coconut",
      "variety": "Coconut",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "2400",
      "max_price": "2600",
      "modal_price": "2500"
    },
    {
      "state": "Uttar Pradesh",
      "district": "Bareilly",
      "market": "Richha",
      "commodity": "Paddy(Dhan)(Common)",
      "variety": "Common",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "2030",
      "max_price": "2055",
      "modal_price": "2040"
    },
    {
      "state": "Bihar",
      "district": "Kishanganj",
      "market": "Bahadurganj",
      "commodity": "Banana",
      "variety": "Amruthapani",
      "grade": "NA",
      "arrival_date": "04/02/2023",
      "min_price": "1800",
      "max_price": "2000",
      "modal_price": "1900"
    }
  ];

  export default Price_data;